{% set name = "gravity-toolkit" %}
{% set version = "1.2.3" %}
{% set sha256 = "4176588380f4b9e55945dc1dac4369765d325fea3793eb8b9f5786e0771566e4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gravity_toolkit-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python
    - boto3
    - cartopy
    - future
    - h5py
    - lxml
    - ipywidgets
    - ipympl
    - jupyterlab
    - jupyterlab_widgets
    - matplotlib-base
    - numpy
    - python >={{ python_min }}
    - python-dateutil
    - pyyaml
    - scipy
    - setuptools

test:
  imports:
    - gravity_toolkit
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tsutterley/gravity-toolkit
  summary: Python tools for working time-variable gravity fields
  license: MIT
  license_file: LICENSE
  description: |
    Python tools for obtaining and working with spherical harmonic coefficients
    from the NASA/DLR GRACE and NASA/GFZ GRACE Follow-on missions
  doc_url: https://gravity-toolkit.readthedocs.io/
  dev_url: https://github.com/tsutterley/gravity-toolkit

extra:
  recipe-maintainers:
    - tsutterley
